/** @type {import('prettier').Config} */
module.exports = {
  printWidth: 90,
  semi: false,
  singleQuote: true,
  tabWidth: 2,
  useTabs: false,
  bracketSpacing: true,
  arrowParens: 'avoid',
  endOfLine: 'auto',
  trailingComma: 'es5',
  importOrder: [
    '^(react/(.*)$)|^(react$)',
    '<THIRD_PARTY_MODULES>',
    '',
    '^~/app/(.*)$',
    '',
    '',
    '^~/lib/(.*)$',
    '',
    '^~/components/ui/(.*)$',
    '^~/components/(.*)$',
    '',
    '^~/store/(.*)$',
    '^~/config/(.*)$',
    '',
    '^~/hooks/(.*)$',
    '^~/constants/(.*)$',
    '',
    '^~/types$',
    '^~/types/(.*)$',
    '',
    '^~/styles/(.*)$',
    '',
    '^[./]',
  ],
  importOrderSeparation: true,
  importOrderSortSpecifiers: true,
  importOrderBuiltinModulesToTop: true,
  importOrderParserPlugins: ['typescript', 'jsx', 'decorators-legacy'],
  importOrderMergeDuplicateImports: true,
  importOrderCombineTypeAndValueImports: true,
  plugins: ['@ianvs/prettier-plugin-sort-imports'],
}
